name: Run Auto Readme Generator # 워크플로우 이름 지정

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.5
      uses: actions/setup-python@v1
      with:
          python-version: '3.9'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./util/generator_requirements.txt
    - name: Auto Readme Generator
      run: |
        python "generator.py"
    - name: Commits
      run: |
        git config --local user.email "tnfxoddl02@gmail.com"
        git config --local user.name "djh0211" 
        git add README.md
        git commit -m "auto - update readme file" # 커밋 메세지
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: ${{secrets.TOKEN}}
